[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GC9A01A@^1.0.4
  adafruit/Adafruit GFX Library@^1.11.9
  bounce2
  ESP32Encoder
  U8g2
